name: "Build Executable"

on:
  push:
    branches:
      - "master"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build executable on ${{ matrix.os }} with g++
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            target: Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Compile the project
        run: g++ -Os -std=gnu++17 -Iinclude main.cpp -o obj/Release/main.o
        
      - name: Create the executable
        run: g++ -o bin/Release/Chess_3.exe obj/Release/main.o -s
            
